// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 00005_pre_go_ticket_item_9999.sql

package database

import (
	"context"
)

const getTicketItemById = `-- name: GetTicketItemById :one
SELECT id, name, stock_initial, stock_available
FROM ticket_item
WHERE id = ?
`

type GetTicketItemByIdRow struct {
	ID             int64
	Name           string
	StockInitial   int32
	StockAvailable int32
}

func (q *Queries) GetTicketItemById(ctx context.Context, id int64) (GetTicketItemByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketItemById, id)
	var i GetTicketItemByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StockInitial,
		&i.StockAvailable,
	)
	return i, err
}
